DATASET_PATH = "/media/andrea/NVMe/Dataset/ReID/Training/"
facial_feature_types = ['type-2-x', 'type-2-y', 'type-3-x', 'type-3-y', 'type-4']
MIN_FACE_OFFSET_X = -70
MAX_FACE_OFFSET_X = 70
MIN_FACE_OFFSET_Y = -100
MAX_FACE_OFFSET_Y = 30
BLOCKSIZE = 50
NUM_SAMPLES = 8
NUM_POINTS_LBP = 10
RADIUS = 10
SAMPLED_PATH = "./sampled/"
