DATASET_PATH = "/media/andrea/20D2-63FB/Training/"
facial_feature_types = ['type-2-x', 'type-2-y', 'type-3-x', 'type-3-y', 'type-4']
MIN_FACE_OFFSET_X = -70
MAX_FACE_OFFSET_X = 70
MIN_FACE_OFFSET_Y = -100
MAX_FACE_OFFSET_Y = 30
BLOCKSIZE = 10
NUM_SAMPLES = 3
NUM_POINTS_LBP = 40
RADIUS = 10
SAMPLED_PATH = "./sampled/"
